language: csharp
solution: Plastiline.Net.sln
mono:
    - latest
install:
  - nuget restore Plastiline.Net.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Plastiline.Net.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Plastiline.Core.Tests/bin/Release/Plastiline.Core.Tests.dll
