language: csharp
solution: Plastiline.Net.sln
mono:
    - latest
install:
  - nuget restore Plastiline.Net.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Plastiline.Net.sln
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./Plastiline.Core.Tests/bin/Release/Plastiline.Core.Tests.dll
